import type { Industry } from './job-constants.js';

export const INDUSTRY_KEYWORDS: Record<Industry, Record<string, number>> = {
  Technology: {
    python: 3, javascript: 3, typescript: 3, java: 2, 'c++': 2, 'c#': 2, go: 2, rust: 2, ruby: 2, php: 2, swift: 2, kotlin: 2,
    react: 3, angular: 3, vue: 3, 'next.js': 3, 'node.js': 3, express: 2, django: 2, flask: 2, spring: 2,
    aws: 3, azure: 3, gcp: 3, 'google cloud': 3,
    docker: 3, kubernetes: 3, k8s: 3, terraform: 3, ansible: 2, jenkins: 2, 'ci/cd': 3,
    'machine learning': 4, 'deep learning': 4, ai: 4, 'artificial intelligence': 4, nlp: 3,
    tensorflow: 4, pytorch: 4, pandas: 2, numpy: 2, scikit: 3, spark: 3, hadoop: 2, kafka: 3,
    'data science': 3, 'data engineering': 3, etl: 2, 'data pipeline': 2, dbt: 2, airflow: 2,
    postgresql: 2, mysql: 2, mongodb: 2, redis: 2, elasticsearch: 2, dynamodb: 2,
    'software engineer': 3, 'software developer': 3, 'full stack': 3, fullstack: 3, frontend: 2, backend: 2,
    saas: 3, api: 2, sdk: 2, git: 2, agile: 2, scrum: 2, microservices: 3, rest: 2, graphql: 3,
    'cloud architecture': 3, 'cloud native': 3, serverless: 3,
    'system design': 3, 'system architecture': 3, scalability: 2,
    cybersecurity: 3, 'cyber security': 3, penetration: 2,
  },
  Healthcare: {
    hipaa: 5, 'patient data': 4, 'electronic health record': 5, ehr: 5, emr: 4,
    'clinical trial': 4, 'clinical data': 4, fda: 3, 'medical device': 4, 'medical imaging': 5,
    dicom: 4, hl7: 4, fhir: 5,
    biotech: 5, biotechnology: 5, pharma: 4, pharmaceutical: 4, genomics: 5, bioinformatics: 4,
    'drug discovery': 4, 'drug development': 4, 'clinical research': 4, pharmacovigilance: 4,
    'health tech': 5, 'healthcare technology': 5, telemedicine: 4, telehealth: 4,
    'life sciences': 4, 'molecular biology': 3, immunology: 3,
    diagnosis: 2, pathology: 3, radiology: 3, oncology: 3, 'public health': 3, epidemiology: 3,
  },
  Finance: {
    banking: 5, 'investment banking': 5, fintech: 5, insurance: 4, insurtech: 4,
    'wealth management': 4, 'asset management': 4, 'private equity': 4, 'venture capital': 4,
    trading: 4, 'algorithmic trading': 5, 'quantitative trading': 5, bloomberg: 4,
    'risk management': 5, compliance: 4, 'regulatory compliance': 4, sec: 3, sox: 3,
    aml: 4, kyc: 4,
    'payment processing': 4, 'payment gateway': 4, stripe: 3, 'digital payment': 3,
    accounting: 3, 'financial reporting': 4, gaap: 3, ifrs: 3, audit: 3,
    'financial analysis': 4, 'financial modeling': 4, valuation: 3,
  },
  Retail: {
    shopify: 5, woocommerce: 4, magento: 4, bigcommerce: 4,
    'e-commerce': 5, ecommerce: 5, marketplace: 4, dtc: 4, 'direct to consumer': 4,
    'retail tech': 4, 'retail technology': 4, retail: 4,
    'point of sale': 4, pos: 3, 'inventory management': 4,
    fulfillment: 4, 'order management': 4, 'last mile': 3, 'drop shipping': 3,
    'shopping cart': 3, checkout: 3, 'product catalog': 3,
    'customer lifetime': 3, conversion: 3, 'ab testing': 3,
  },
  Manufacturing: {
    'six sigma': 5, 'lean manufacturing': 5, 'quality assurance': 4, iso: 4,
    cad: 4, autocad: 3, solidworks: 4, catia: 3,
    'supply chain': 5, 'supply chain management': 5, scm: 4, logistics: 4, procurement: 4,
    erp: 4, sap: 3, inventory: 3, 'demand planning': 4,
    automotive: 4, aerospace: 4, semiconductor: 4, electronics: 3,
    automation: 3, plc: 3, scada: 3, robotics: 3, 'industrial automation': 4,
    osha: 3, 'workplace safety': 3,
  },
  Education: {
    edtech: 5, 'e-learning': 5, elearning: 5, 'online learning': 4,
    lms: 5, 'learning management': 5, moodle: 3, canvas: 2,
    curriculum: 3, 'instructional design': 5, 'course design': 4,
    'educational content': 4, assessment: 3, 'learning analytics': 4,
    'corporate training': 4, 'professional development': 3,
    'higher education': 3, k12: 3, 'k-12': 3,
    'adaptive learning': 4, 'personalized learning': 4,
  },
  Government: {
    'public sector': 5, government: 5, federal: 4, state: 3, municipal: 3,
    'defense contractor': 4, dod: 3, 'intelligence community': 4,
    'public policy': 3, 'civic tech': 4, 'government technology': 4,
    'compliance': 3, 'regulatory': 3,
  },
  Construction: {
    construction: 5, 'civil engineering': 5, 'structural engineering': 4,
    architect: 3, 'project management': 3, 'site management': 4,
    'real estate': 3, building: 3, infrastructure: 4,
    'health and safety': 3, 'building codes': 4, zoning: 3,
  },
  Telecom: {
    telecom: 5, telecommunications: 5, '5g': 4, '4g': 3, lte: 3,
    networking: 4, 'network engineering': 4, cisco: 3,
    'fiber optic': 3, broadband: 3, isp: 3, voip: 3,
    'mobile network': 3, 'wireless': 3, satellite: 3,
  },
  Insurance: {
    insurance: 5, insurtech: 5, underwriting: 5, claims: 4,
    actuarial: 5, 'risk assessment': 4, 'policy administration': 4,
    'reinsurance': 4, 'property and casualty': 4, life: 3,
    'health insurance': 4, 'insurance technology': 4,
  },
  Legal: {
    legal: 5, law: 4, 'legal tech': 5, 'legal technology': 5,
    compliance: 4, regulatory: 3, 'contract management': 4,
    'legal research': 4, litigation: 4, 'intellectual property': 4, ip: 3,
    'legal operations': 4, paralegal: 3, 'legal counsel': 4,
  },
  Automotive: {
    automotive: 5, vehicle: 4, 'autonomous driving': 5, 'self-driving': 5,
    ev: 4, 'electric vehicle': 5, 'electric car': 5,
    adas: 4, 'advanced driver': 4, 'in-vehicle': 4,
    oem: 3, 'tier 1': 3, 'automotive software': 4,
  },
  Energy: {
    energy: 5, 'renewable energy': 5, solar: 4, wind: 3, hydro: 3,
    oil: 3, gas: 3, 'oil and gas': 4, petroleum: 3,
    'power generation': 4, 'smart grid': 4, 'energy storage': 4,
    'carbon capture': 3, sustainability: 3, 'clean energy': 4,
  },
  Media: {
    media: 5, entertainment: 4, 'content creation': 4, broadcasting: 4,
    streaming: 4, 'digital media': 5, 'social media': 4,
    publishing: 3, 'video production': 3, 'audio production': 3,
    advertising: 4, 'ad tech': 4, programmatic: 3,
  },
  Agriculture: {
    agriculture: 5, agritech: 5, 'ag tech': 5, farming: 4,
    'precision agriculture': 5, 'agricultural technology': 5,
    'food production': 3, 'supply chain': 2, irrigation: 3,
    'crop management': 4, 'livestock': 3, agronomy: 4,
  },
  Other: {
    management: 1, leadership: 1, strategy: 1, operations: 1, consulting: 1,
    marketing: 1, sales: 1, hr: 1, 'human resources': 1,
    recruiting: 1, 'talent acquisition': 1, 'project management': 1,
  },
};
