export const DEGREE_ALIASES: Record<string, string> = {
  'b.tech': 'Bachelor of Technology',
  'btech': 'Bachelor of Technology',
  'b. tech': 'Bachelor of Technology',
  'bachelor of technology': 'Bachelor of Technology',
  'm.tech': 'Master of Technology',
  'mtech': 'Master of Technology',
  'm. tech': 'Master of Technology',
  'master of technology': 'Master of Technology',
  'bachelor': 'Bachelor\'s Degree',
  'bachelors': 'Bachelor\'s Degree',
  'master': 'Master\'s Degree',
  'masters': 'Master\'s Degree',
  'phd': 'Ph.D.',
  'ph.d': 'Ph.D.',
  'ph.d.': 'Ph.D.',
  'doctorate': 'Ph.D.',
  'doctoral': 'Ph.D.',
  'mba': 'MBA',
  'bca': 'BCA',
  'mca': 'MCA',
  'bsc': 'B.Sc.',
  'msc': 'M.Sc.',
  'b.s.': 'B.S.',
  'm.s.': 'M.S.',
  'b.e.': 'B.E.',
  'm.e.': 'M.E.',
  'be': 'B.E.',
  'me': 'M.E.',
  'associate': 'Associate\'s Degree',
  'associates': 'Associate\'s Degree',
  'diploma': 'Diploma',
  'certificate': 'Certificate',
  'professional certificate': 'Professional Certificate',
  'nanodegree': 'Nanodegree',
  'specialization': 'Specialization',
  'executive': 'Executive Education',
  'fellowship': 'Fellowship',
  'bachelor of': 'Bachelor\'s Degree',
  'master of': 'Master\'s Degree',
  'postgraduate': 'Postgraduate',
  'undergraduate': 'Undergraduate',
  'bba': 'B.B.A.',
  'b.com': 'B.Com.',
  'm.com': 'M.Com.',
  'b.arch': 'B.Arch.',
  'm.arch': 'M.Arch.',
  'b.farm': 'B.Pharm.',
  'm.farm': 'M.Pharm.',
  'llb': 'LLB',
  'llm': 'LLM',
  'b.des': 'B.Des.',
  'm.des': 'M.Des.',
  'bfa': 'B.F.A.',
  'mfa': 'M.F.A.',
  'bhm': 'B.H.M.',
  'mhsm': 'M.H.S.M.',
  'b.ed': 'B.Ed.',
  'm.ed': 'M.Ed.',
  'bps': 'B.P.S.',
  'mps': 'M.P.S.',
};

export const EDUCATION_LEVEL_MAP: Record<string, string> = {
  'high school': 'secondary',
  'secondary': 'secondary',
  'diploma': 'secondary',
  'class x': 'secondary',
  'class xi': 'secondary',
  'class xii': 'secondary',
  'cbse': 'secondary',
  'icse': 'secondary',
  'associate': 'associate',
  'bachelor': 'bachelor',
  'undergraduate': 'bachelor',
  'b.tech': 'bachelor',
  'btech': 'bachelor',
  'bca': 'bachelor',
  'bsc': 'bachelor',
  'b.s.': 'bachelor',
  'b.e.': 'bachelor',
  'bba': 'bachelor',
  'b.com': 'bachelor',
  'b.arch': 'bachelor',
  'b.farm': 'bachelor',
  'llb': 'bachelor',
  'b.des': 'bachelor',
  'bfa': 'bachelor',
  'bhm': 'bachelor',
  'b.ed': 'bachelor',
  'master': 'master',
  'postgraduate': 'master',
  'm.tech': 'master',
  'mtech': 'master',
  'mca': 'master',
  'msc': 'master',
  'm.s.': 'master',
  'm.e.': 'master',
  'mba': 'master',
  'm.com': 'master',
  'm.arch': 'master',
  'm.farm': 'master',
  'llm': 'master',
  'm.des': 'master',
  'mfa': 'master',
  'mhsm': 'master',
  'm.ed': 'master',
  'phd': 'doctorate',
  'ph.d': 'doctorate',
  'ph.d.': 'doctorate',
  'doctorate': 'doctorate',
  'doctoral': 'doctorate',
  'nanodegree': 'certificate',
  'certificate': 'certificate',
  'professional certificate': 'certificate',
  'specialization': 'certificate',
};
