export const SKILL_CATEGORIES: Record<string, string> = {
  // Languages
  'javascript': 'language', 'typescript': 'language', 'python': 'language', 'java': 'language',
  'c++': 'language', 'c#': 'language', 'go': 'language', 'rust': 'language', 'ruby': 'language',
  'php': 'language', 'swift': 'language', 'kotlin': 'language', 'scala': 'language',
  'r': 'language', 'matlab': 'language', 'sql': 'language', 'html': 'language', 'css': 'language',
  'sass': 'language', 'scss': 'language', 'less': 'language', 'dart': 'language', 'lua': 'language',
  'haskell': 'language', 'elixir': 'language', 'clojure': 'language', 'f#': 'language',
  'perl': 'language', 'cobol': 'language', 'fortran': 'language', 'assembly': 'language',
  'groovy': 'language', 'powershell': 'language', 'bash': 'language', 'shell': 'language',
  'objective-c': 'language', 'visual basic': 'language', 'vba': 'language',
  // Frameworks
  'react': 'framework', 'vue': 'framework', 'angular': 'framework', 'svelte': 'framework',
  'nextjs': 'framework', 'next.js': 'framework', 'nuxt': 'framework', 'remix': 'framework',
  'astro': 'framework', 'sveltekit': 'framework', 'solidjs': 'framework', 'qwik': 'framework',
  'node.js': 'framework', 'nodejs': 'framework', 'express': 'framework', 'fastify': 'framework',
  'fastapi': 'framework', 'django': 'framework', 'flask': 'framework', 'spring': 'framework',
  'spring boot': 'framework', 'rails': 'framework', 'laravel': 'framework', 'symfony': 'framework',
  'tailwind': 'framework', 'bootstrap': 'framework', 'material-ui': 'framework', 'chakra ui': 'framework',
  'ant design': 'framework', 'shadcn': 'framework', 'styled-components': 'framework',
  'tensorflow': 'framework', 'pytorch': 'framework', 'keras': 'framework', 'scikit-learn': 'framework',
  'pandas': 'framework', 'numpy': 'framework', 'matplotlib': 'framework', 'seaborn': 'framework',
  'plotly': 'framework', 'hugging face': 'framework', 'transformers': 'framework', 'langchain': 'framework',
  'llamaindex': 'framework', 'openai': 'framework', 'cohere': 'framework',
  'dotnet': 'framework', '.net': 'framework', 'asp.net': 'framework', 'blazor': 'framework',
  'xamarin': 'framework', 'maui': 'framework', 'flutter': 'framework', 'react native': 'framework',
  'ionic': 'framework', 'cordova': 'framework', 'electron': 'framework', 'tauri': 'framework',
  // Tools
  'git': 'tool', 'github': 'tool', 'gitlab': 'tool', 'bitbucket': 'tool',
  'jira': 'tool', 'confluence': 'tool', 'slack': 'tool', 'figma': 'tool',
  'notion': 'tool', 'docker': 'tool', 'kubernetes': 'tool', 'k8s': 'tool',
  'terraform': 'tool', 'ansible': 'tool', 'jenkins': 'tool', 'circleci': 'tool',
  'postman': 'tool', 'swagger': 'tool', 'webpack': 'tool', 'vite': 'tool',
  'esbuild': 'tool', 'rollup': 'tool', 'parcel': 'tool', 'bun': 'tool', 'deno': 'tool',
  'grunt': 'tool', 'gulp': 'tool', 'npm': 'tool', 'yarn': 'tool', 'pnpm': 'tool',
  'maven': 'tool', 'gradle': 'tool', 'nuget': 'tool', 'pip': 'tool', 'conda': 'tool',
  'helm': 'tool', 'kustomize': 'tool', 'packer': 'tool', 'vagrant': 'tool',
  'prometheus': 'tool', 'grafana': 'tool', 'datadog': 'tool', 'new relic': 'tool', 'splunk': 'tool',
  'asana': 'tool', 'trello': 'tool', 'monday.com': 'tool',
  'miro': 'tool', 'lucidchart': 'tool', 'draw.io': 'tool',
  'visual studio': 'tool', 'vs code': 'tool', 'intellij': 'tool', 'eclipse': 'tool',
  'vim': 'tool', 'neovim': 'tool', 'emacs': 'tool', 'sublime': 'tool',
  'chrome devtools': 'tool', 'insomnia': 'tool',
  // Platforms
  'aws': 'platform', 'gcp': 'platform', 'azure': 'platform', 'firebase': 'platform',
  'heroku': 'platform', 'vercel': 'platform', 'netlify': 'platform', 'digitalocean': 'platform',
  'linux': 'platform', 'unix': 'platform', 'windows': 'platform', 'macos': 'platform',
  'ios': 'platform', 'android': 'platform', 'chrome os': 'platform', 'wasm': 'platform',
  'cloudflare': 'platform', 'fastly': 'platform', 'akamai': 'platform',
  // Databases
  'postgresql': 'database', 'postgres': 'database', 'mysql': 'database', 'mongodb': 'database',
  'redis': 'database', 'elasticsearch': 'database', 'dynamodb': 'database', 'cassandra': 'database',
  'neo4j': 'database', 'sqlite': 'database', 'mssql': 'database', 'oracle db': 'database',
  'couchdb': 'database', 'influxdb': 'database', 'timescaledb': 'database', 'cockroachdb': 'database',
  'mariadb': 'database', 'firebase firestore': 'database', 'supabase': 'database',
  'prisma': 'database', 'typeorm': 'database', 'sequelize': 'database', 'knex': 'database',
  'graphql': 'database', 'grpc': 'database',
  // Cloud / DevOps Services
  'lambda': 'platform', 'ecs': 'platform', 'eks': 'platform', 'fargate': 'platform',
  's3': 'platform', 'rds': 'platform', 'ec2': 'platform', 'cloudfront': 'platform',
  'route53': 'platform', 'api gateway': 'platform', 'sqs': 'platform', 'sns': 'platform',
  'step functions': 'platform', 'glacier': 'platform', 'athena': 'platform', 'redshift': 'platform',
  'emr': 'platform', 'kinesis': 'platform', 'cloudwatch': 'platform', 'iam': 'platform',
  'secret manager': 'platform', 'codepipeline': 'platform', 'codebuild': 'platform',
  'cloud functions': 'platform', 'cloud run': 'platform', 'app engine': 'platform',
  'bigquery': 'platform', 'dataflow': 'platform', 'pub/sub': 'platform', 'composer': 'platform',
  'kubernetes engine': 'platform', 'container registry': 'platform',
  'azure devops': 'platform', 'azure functions': 'platform', 'azure cosmos': 'platform',
  'azure ml': 'platform', 'azure data lake': 'platform', 'power bi': 'platform',
  // Concepts
  'machine learning': 'concept', 'ml': 'concept', 'ai': 'concept', 'artificial intelligence': 'concept',
  'deep learning': 'concept', 'nlp': 'concept', 'llm': 'concept', 'data science': 'concept',
  'microservices': 'concept', 'rest': 'concept', 'rest api': 'concept',
  'ci/cd': 'concept', 'devops': 'concept', 'agile': 'concept', 'scrum': 'concept',
  'test driven development': 'concept', 'tdd': 'concept', 'oop': 'concept',
  'data structures': 'concept', 'algorithms': 'concept', 'design patterns': 'concept',
  'rag': 'concept', 'vector database': 'concept', 'embedding': 'concept', 'fine-tuning': 'concept',
  'prompt engineering': 'concept', 'agent': 'concept', 'multi-agent': 'concept',
  'infrastructure as code': 'concept', 'containerization': 'concept', 'orchestration': 'concept',
  'serverless': 'concept', 'event-driven': 'concept', 'cqrs': 'concept', 'event sourcing': 'concept',
  'domain driven design': 'concept', 'ddd': 'concept', 'micro frontends': 'concept',
  'monorepo': 'concept', 'polyrepo': 'concept', 'shift left': 'concept',
  'observability': 'concept', 'chaos engineering': 'concept', 'site reliability': 'concept', 'sre': 'concept',
  'zero trust': 'concept', 'oauth': 'concept', 'jwt': 'concept', 'sso': 'concept',
  'mlops': 'concept', 'dataops': 'concept', 'finops': 'concept', 'gitops': 'concept',
  'pair programming': 'concept', 'mob programming': 'concept',
  'lean': 'concept',
  'saas': 'concept', 'paas': 'concept', 'iaas': 'concept',
  'multi-tenancy': 'concept',
  'feature flags': 'concept', 'canary deployment': 'concept', 'blue-green deployment': 'concept',
  // Healthcare
  'hipaa': 'concept', 'ehr': 'tool', 'epic': 'tool', 'cerner': 'tool',
  'patient assessment': 'concept', 'vital signs': 'concept', 'phlebotomy': 'concept',
  'medical terminology': 'concept', 'anatomy': 'concept', 'pharmacology': 'concept',
  'clinical trials': 'concept', 'patient care': 'concept', 'medical records': 'concept',
  'icd-10': 'concept', 'cpt coding': 'concept', 'medical imaging': 'concept',
  'radiology': 'concept', 'sonography': 'concept', 'physical therapy': 'concept',
  'occupational therapy': 'concept', 'speech therapy': 'concept', 'nursing': 'concept',
  'surgery': 'concept', 'emergency medicine': 'concept', 'internal medicine': 'concept',
  'pediatrics': 'concept', 'obstetrics': 'concept', 'cardiology': 'concept',
  'oncology': 'concept', 'neurology': 'concept', 'psychiatry': 'concept',
  'dermatology': 'concept', 'ophthalmology': 'concept', 'anesthesiology': 'concept',
  'pathology': 'concept', 'public health': 'concept', 'epidemiology': 'concept',
  'biostatistics': 'concept', 'health informatics': 'concept',
  'bls': 'concept', 'acls': 'concept', 'pals': 'concept', 'cpr': 'concept',
  'rn': 'concept', 'md': 'concept', 'np': 'concept', 'pa': 'concept',
  'bsn': 'concept', 'msn': 'concept',
  // Finance
  'financial modeling': 'concept', 'valuation': 'concept', 'dcf': 'concept', 'lbo': 'concept',
  'wacc': 'concept', 'ev/ebitda': 'concept', 'risk analysis': 'concept', 'compliance': 'concept',
  'aml': 'concept', 'kyc': 'concept', 'sox': 'concept', 'audit': 'concept',
  'tax accounting': 'concept', 'forensic accounting': 'concept', 'portfolio management': 'concept',
  'asset allocation': 'concept', 'equities': 'concept', 'fixed income': 'concept',
  'derivatives': 'concept', 'options': 'concept', 'futures': 'concept', 'credit analysis': 'concept',
  'underwriting': 'concept', 'actuarial': 'concept',
  'series 7': 'concept', 'series 66': 'concept', 'cfa': 'concept', 'cpa': 'concept',
  'frm': 'concept', 'caia': 'concept',
  'bloomberg terminal': 'tool', 'capital markets': 'concept', 'investment banking': 'concept',
  'wealth management': 'concept', 'hedge fund': 'concept', 'private equity': 'concept',
  'venture capital': 'concept', 'mutual fund': 'concept', 'etf': 'concept',
  'derivatives pricing': 'concept', 'quantitative analysis': 'concept',
  // Creative / Design
  'sketch': 'tool', 'adobe xd': 'tool', 'photoshop': 'tool',
  'illustrator': 'tool', 'indesign': 'tool', 'after effects': 'tool', 'premiere pro': 'tool',
  'lightroom': 'tool', '3ds max': 'tool', 'blender': 'tool', 'cinema 4d': 'tool',
  'maya': 'tool', 'zbrush': 'tool', 'procreate': 'tool', 'canva': 'tool',
  'invision': 'tool', 'marvel': 'tool', 'zeplin': 'tool', 'balsamiq': 'tool',
  'axure': 'tool', 'principle': 'tool', 'framer': 'tool', 'origami': 'tool',
  'proto.io': 'tool', 'user research': 'concept', 'wireframing': 'concept',
  'prototyping': 'concept', 'design systems': 'concept', 'typography': 'concept',
  'color theory': 'concept', 'ui/ux': 'concept', 'motion graphics': 'concept',
  'brand identity': 'concept', 'graphic design': 'concept', 'video editing': 'concept',
  '3d modeling': 'concept', 'animation': 'concept', 'storyboarding': 'concept',
  // Engineering / Manufacturing
  'autocad': 'tool', 'solidworks': 'tool', 'catia': 'tool', 'nx': 'tool',
  'creo': 'tool', 'inventor': 'tool', 'simulink': 'tool', 'ansys': 'tool',
  'solid edge': 'tool', 'fusion 360': 'tool', 'revit': 'tool', 'archicad': 'tool',
  'six sigma': 'concept', 'lean manufacturing': 'concept',
  'iso 9001': 'concept', 'iso 14001': 'concept', 'iso 45001': 'concept',
  'gd&t': 'concept', 'cnc': 'tool', 'plc': 'tool', 'scada': 'tool', 'labview': 'tool',
  'quality assurance': 'concept', 'root cause analysis': 'concept', 'fmea': 'concept',
  'apqp': 'concept', 'ppap': 'concept', 'spc': 'concept', 'msa': 'concept',
  '8d': 'concept', 'kaizen': 'concept', '5s': 'concept', 'kanban': 'concept',
  'oee': 'concept', 'mtbf': 'concept', 'reliability engineering': 'concept',
  'value engineering': 'concept', 'tolerance stackup': 'concept', 'fatigue analysis': 'concept',
  // Sales / Marketing
  'salesforce': 'tool', 'hubspot': 'tool', 'marketo': 'tool', 'pardot': 'tool',
  'google analytics': 'tool', 'google ads': 'tool', 'facebook ads': 'tool', 'linkedin ads': 'tool',
  'seo': 'concept', 'sem': 'concept', 'ppc': 'concept', 'email marketing': 'concept',
  'content marketing': 'concept', 'social media marketing': 'concept',
  'inbound marketing': 'concept', 'outbound marketing': 'concept',
  'ab testing': 'concept', 'conversion rate optimization': 'concept',
  'lead generation': 'concept', 'pipeline management': 'concept',
  'crm': 'tool', 'account based marketing': 'concept', 'customer success': 'concept',
  'customer retention': 'concept', 'churn reduction': 'concept',
  'marketing automation': 'concept', 'copywriting': 'concept', 'growth hacking': 'concept',
  // Soft Skills / Methodology
  'stakeholder management': 'concept', 'cross-functional leadership': 'concept',
  'mentoring': 'concept', 'public speaking': 'concept', 'technical writing': 'concept',
  'requirements gathering': 'concept', 'user stories': 'concept', 'sprint planning': 'concept',
  'product roadmaps': 'concept', 'go-to-market': 'concept', 'competitive analysis': 'concept',
  'market research': 'concept', 'okr': 'concept', 'kpi': 'concept',
  'data-driven': 'concept', 'strategic planning': 'concept', 'vendor management': 'concept',
  'budget management': 'concept', 'p&l': 'concept', 'change management': 'concept',
  'risk management': 'concept', 'business analysis': 'concept', 'process improvement': 'concept',
  'project management': 'concept', 'program management': 'concept', 'product management': 'concept',
  'pmp': 'concept', 'prince2': 'concept', 'itil': 'concept', 'cobit': 'concept',
};

export const SKILL_ALIASES: Record<string, string> = {
  'js': 'javascript',
  'ts': 'typescript',
  'py': 'python',
  'rb': 'ruby',
  'k8s': 'kubernetes',
  'tf': 'tensorflow',
  'sklearn': 'scikit-learn',
  'np': 'numpy',
  'pd': 'pandas',
  'ms': 'mssql',
  'pg': 'postgresql',
  'mongo': 'mongodb',
  'es': 'elasticsearch',
  'aws': 'aws',
  'gcp': 'gcp',
  'azure': 'azure',
  'react.js': 'react',
  'reactjs': 'react',
  'vue.js': 'vue',
  'vuejs': 'vue',
  'angular.js': 'angular',
  'angularjs': 'angular',
  'node': 'node.js',
  'nodejs': 'node.js',
  'next': 'next.js',
  'nextjs': 'next.js',
  'tailwindcss': 'tailwind',
  'mui': 'material-ui',
  'postgres': 'postgresql',
  'ms sql': 'mssql',
  'sql server': 'mssql',
  'ms sql server': 'mssql',
  'dot net': '.net',
  'dotnet': '.net',
  'c-sharp': 'c#',
  'cpp': 'c++',
  'objectivec': 'objective-c',
  'objective-c': 'objective-c',
  'vb': 'visual basic',
  'vba': 'vba',
  'golang': 'go',
  'shell scripting': 'shell',
  'bash scripting': 'bash',
  'powershell scripting': 'powershell',
  'ps': 'powershell',
  'machine-learning': 'machine learning',
  'deep-learning': 'deep learning',
  'artificial-intelligence': 'artificial intelligence',
  'data-science': 'data science',
  'ci-cd': 'ci/cd',
  'ci / cd': 'ci/cd',
  'restful': 'rest',
  'rest api': 'rest',
  'restful api': 'rest',
  'rest apis': 'rest',
  'restful services': 'rest',
  'restful web': 'rest',
  'graphql': 'graphql',
  'gql': 'graphql',
  'grpc': 'grpc',
  'remote procedure call': 'grpc',
  'rpc': 'grpc',
  'grpc protocol': 'grpc',
  'grpc api': 'grpc',
  'grpc service': 'grpc',
  'grpc client': 'grpc',
  'grpc server': 'grpc',
};
